baseURL = 'https://sylvainconny.github.io/cours-eanis/'
languageCode = 'fr-FR'
title = 'Cours EANIS'
#theme = 'hugo-theme-relearn'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'