baseURL = 'https://sylvainconny.github.io/cours-eanis/'
languageCode = 'fr-FR'
title = 'Cours EANIS'
defaultContentLanguage = 'fr'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[linkEffects]
  download = false
  target = '_blank'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  page = ['html', 'print']